"""
Enhanced component constants for genetic circuit modeling
Based on realistic biological parameters from Version 15.3
"""

COMPONENT_CONSTANTS = {
    # Promoters - From working notebook constants
    "promoter_1": {"strength": 5.0, "type": "promoter"},
    "promoter_2": {"strength": 5.0, "type": "promoter"},
    "promoter_3": {"strength": 5.0, "type": "promoter"},
    "promoter_4": {"strength": 5.0, "type": "promoter"},
    "promoter_5": {"strength": 5.0, "type": "promoter"},
    "promoter_6": {"strength": 5.0, "type": "promoter"},
    "promoter_7": {"strength": 5.0, "type": "promoter"},
    "promoter_8": {"strength": 5.0, "type": "promoter"},
    "promoter_9": {"strength": 5.0, "type": "promoter"},
    "promoter_10": {"strength": 5.0, "type": "promoter"},
    "promoter_11": {"strength": 5.0, "type": "promoter"},
    "promoter_12": {"strength": 5.0, "type": "promoter"},
    "promoter_13": {"strength": 5.0, "type": "promoter"},
    "promoter_14": {"strength": 5.0, "type": "promoter"},
    "promoter_15": {"strength": 5.0, "type": "promoter"},
    
    # RBS - From working notebook constants
    "rbs_1": {"efficiency": 1.0, "type": "rbs"},
    "rbs_2": {"efficiency": 1.0, "type": "rbs"},
    "rbs_3": {"efficiency": 1.0, "type": "rbs"},
    "rbs_4": {"efficiency": 1.0, "type": "rbs"},
    "rbs_5": {"efficiency": 1.0, "type": "rbs"},
    "rbs_6": {"efficiency": 1.0, "type": "rbs"},
    "rbs_7": {"efficiency": 1.0, "type": "rbs"},
    "rbs_8": {"efficiency": 1.0, "type": "rbs"},
    "rbs_9": {"efficiency": 1.0, "type": "rbs"},
    "rbs_10": {"efficiency": 1.0, "type": "rbs"},
    "rbs_11": {"efficiency": 1.0, "type": "rbs"},
    "rbs_12": {"efficiency": 1.0, "type": "rbs"},
    "rbs_13": {"efficiency": 1.0, "type": "rbs"},
    "rbs_14": {"efficiency": 1.0, "type": "rbs"},
    "rbs_15": {"efficiency": 1.0, "type": "rbs"},
    
    # CDS - From working notebook constants
    "cds_1": {"degradation_rate": 1.0, "translation_rate": 7.0, "init_conc": 0.0, "type": "cds"},
    "cds_2": {"degradation_rate": 1.0, "translation_rate": 7.0, "init_conc": 0.0, "type": "cds"},
    "cds_3": {"degradation_rate": 1.0, "translation_rate": 7.0, "init_conc": 0.0, "type": "cds"},
    "cds_4": {"degradation_rate": 1.0, "translation_rate": 7.0, "init_conc": 0.0, "type": "cds"},
    "cds_5": {"degradation_rate": 1.0, "translation_rate": 7.0, "init_conc": 0.0, "type": "cds"},
    "cds_6": {"degradation_rate": 1.0, "translation_rate": 7.0, "init_conc": 0.0, "type": "cds"},
    "cds_7": {"degradation_rate": 1.0, "translation_rate": 7.0, "init_conc": 0.0, "type": "cds"},
    "cds_8": {"degradation_rate": 1.0, "translation_rate": 7.0, "init_conc": 0.0, "type": "cds"},
    "cds_9": {"degradation_rate": 1.0, "translation_rate": 7.0, "init_conc": 0.0, "type": "cds"},
    "cds_10": {"degradation_rate": 1.0, "translation_rate": 7.0, "init_conc": 0.0, "type": "cds"},
    "cds_11": {"degradation_rate": 1.0, "translation_rate": 7.0, "init_conc": 0.0, "type": "cds"},
    "cds_12": {"degradation_rate": 1.0, "translation_rate": 7.0, "init_conc": 0.0, "type": "cds"},
    "cds_13": {"degradation_rate": 1.0, "translation_rate": 7.0, "init_conc": 0.0, "type": "cds"},
    "cds_14": {"degradation_rate": 1.0, "translation_rate": 7.0, "init_conc": 0.0, "type": "cds"},
    "cds_15": {"degradation_rate": 1.0, "translation_rate": 7.0, "init_conc": 0.0, "type": "cds"},
    
    # Terminators - From working notebook constants  
    "terminator_1": {"efficiency": 0.99, "type": "terminator"},
    "terminator_2": {"efficiency": 0.99, "type": "terminator"},
    "terminator_3": {"efficiency": 0.99, "type": "terminator"},
    "terminator_4": {"efficiency": 0.99, "type": "terminator"},
    "terminator_5": {"efficiency": 0.99, "type": "terminator"},
    "terminator_6": {"efficiency": 0.99, "type": "terminator"},
    "terminator_7": {"efficiency": 0.99, "type": "terminator"},
    "terminator_8": {"efficiency": 0.99, "type": "terminator"},
    "terminator_9": {"efficiency": 0.99, "type": "terminator"},
    "terminator_10": {"efficiency": 0.99, "type": "terminator"},
    "terminator_11": {"efficiency": 0.99, "type": "terminator"},
    "terminator_12": {"efficiency": 0.99, "type": "terminator"},
    "terminator_13": {"efficiency": 0.99, "type": "terminator"},
    "terminator_14": {"efficiency": 0.99, "type": "terminator"},
    "terminator_15": {"efficiency": 0.99, "type": "terminator"},
    
    # Software format: repressor_start_1, repressor_start_2, etc.
    
    # Hardware format: repressor_a_start, repressor_b_start, etc.
    "repressor_1_start": {"Kr": 0.5, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_1_end": {"Kr": 0.5, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_2_start": {"Kr": 0.1, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_2_end": {"Kr": 0.1, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_3_start": {"Kr": 0.4, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_3_end": {"Kr": 0.4, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_4_start": {"Kr": 0.5, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_4_end": {"Kr": 0.5, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_5_start": {"Kr": 0.5, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_5_end": {"Kr": 0.5, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_6_start": {"Kr": 0.5, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_6_end": {"Kr": 0.5, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_7_start": {"Kr": 0.5, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_7_end": {"Kr": 0.5, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_8_start": {"Kr": 0.5, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_8_end": {"Kr": 0.5, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_9_start": {"Kr": 0.5, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_9_end": {"Kr": 0.5, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_10_start": {"Kr": 0.5, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_10_end": {"Kr": 0.5, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_11_start": {"Kr": 0.5, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_11_end": {"Kr": 0.5, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_12_start": {"Kr": 0.5, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_12_end": {"Kr": 0.5, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_13_start": {"Kr": 0.5, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_13_end": {"Kr": 0.5, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_14_start": {"Kr": 0.5, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_14_end": {"Kr": 0.5, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_15_start": {"Kr": 0.5, "n": 2, "type": "repressor", "is_floating": False},
    "repressor_15_end": {"Kr": 0.5, "n": 2, "type": "repressor", "is_floating": False},
    
    
    # Hardware format: activator_a_start, activator_b_start, etc.
    "activator_1_start": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_1_end": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_2_start": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_2_end": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_3_start": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_3_end": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_4_start": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_4_end": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_5_start": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_5_end": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_6_start": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_6_end": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_7_start": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_7_end": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_8_start": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_8_end": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_9_start": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_9_end": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_10_start": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_10_end": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_11_start": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_11_end": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_12_start": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_12_end": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_13_start": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_13_end": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_14_start": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_14_end": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_15_start": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},
    "activator_15_end": {"Ka": 0.4, "n": 2, "type": "activator", "is_floating": False},

    # Hardware format: inducer_a_start, inducer_b_start, etc.
    "inducer_1_start": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_1_end": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_2_start": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_2_end": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_3_start": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_3_end": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_4_start": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_4_end": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_5_start": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_5_end": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_6_start": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_6_end": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_7_start": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_7_end": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_8_start": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_8_end": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_9_start": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_9_end": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_10_start": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_10_end": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_11_start": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_11_end": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_12_start": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_12_end": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_13_start": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_13_end": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_14_start": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_14_end": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_15_start": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},
    "inducer_15_end": {"Ka": 0.5, "n": 2, "type": "inducer", "is_floating": False},

    # Hardware format: inhibitor_a_start, inhibitor_b_start, etc.
    "inhibitor_1_start": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_1_end": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_2_start": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_2_end": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_3_start": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_3_end": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_4_start": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_4_end": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_5_start": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_5_end": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_6_start": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_6_end": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_7_start": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_7_end": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_8_start": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_8_end": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_9_start": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_9_end": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_10_start": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_10_end": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_11_start": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_11_end": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_12_start": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_12_end": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_13_start": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_13_end": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_14_start": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_14_end": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_15_start": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    "inhibitor_15_end": {"Kr": 0.5, "n": 2, "type": "inhibitor", "is_floating": False},
    
    # Floating regulators - From working notebook constants
    "floating_inhibitor_a": {"Kr": 0.5, "n": 2, "concentration": 1.0, "type": "inhibitor", "is_floating": True},
    "floating_inhibitor_b": {"Kr": 0.5, "n": 2, "concentration": 1.0, "type": "inhibitor", "is_floating": True},
    "floating_inhibitor_c": {"Kr": 0.5, "n": 2, "concentration": 1.0, "type": "inhibitor", "is_floating": True},
    "floating_inducer_a": {"Ka": 0.5, "n": 2, "concentration": 1.0, "type": "inducer", "is_floating": True},
    "floating_inducer_b": {"Ka": 0.5, "n": 2, "concentration": 1.0, "type": "inducer", "is_floating": True},
    "floating_inducer_c": {"Ka": 0.5, "n": 2, "concentration": 1.0, "type": "inducer", "is_floating": True}
}

# Parameter ranges for dial mode
PARAMETER_RANGES = {
    "strength": (0.1, 5.0),
    "efficiency": (0.1, 2.0),
    "translation_rate": (1.0, 20.0),
    "degradation_rate": (0.01, 1.0),
    "binding_affinity": (0.01, 1.0),
    "cooperativity": (0.5, 3.0),
    "max_expression": (10.0, 500.0),
    "global_transcription_rate": (0.1, 3.0),
    "global_translation_rate": (0.1, 3.0),
    "global_degradation_rate": (0.1, 3.0),
    "temperature_factor": (0.5, 2.0),
    "resource_availability": (0.1, 2.0)
}
